In [92]:
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import seaborn as sns
# name_of_movies = df["Name_of_movie"]
# poster_url = df["Poster_url_"]
# director_name = df["Name_of_director"]
# list_of_genre = df["List_of_genre"]
# language_of_move = df["Language_of_move"]
# Names_of_Cast = df["Names_of_Cast"]

In [3]:
# here i have read the original csv
df = pd.read_csv("movieData1.csv")



In [8]:



df.isnull().sum()
df = df.dropna()

In [9]:
df.isnull().sum()

Unnamed: 0              0
Name_of_movie           0
Name_of_director        0
List_of_genre           0
Discription_of_movie    0
Run_time_in_min         0
Language_of_move        0
Country_of_origin       0
Budget_of_movie         0
Global_collection       0
Release_year            0
Rating_out_of_ten       0
World_Wild_Views        0
Reviews_to_movie        0
Names_of_Cast           0
Poster_url_             0
dtype: int64

In [10]:
df = df.rename(columns={"Unnamed: 0": "UniqueID"})

In [12]:
df

UniqueID                Name_of_movie            Name_of_director  \
0            0  Monarch: Legacy of Monsters                Matt Shakman   
1            1                        Andor              Benjamin Caron   
2            2     Avatar: The Way of Water               James Cameron   
3            3                The Equalizer               Antoine Fuqua   
4            4             The Last Kingdom           Edward Bazalgette   
...        ...                          ...                         ...   
1109       245                The 400 Blows           François Truffaut   
1110       246                      Persona              Ingmar Bergman   
1111       247                Life of Brian                 Terry Jones   
1112       248                      Aladdin   Ron Clements, John Musker   
1113       249           Dances with Wolves               Kevin Costner   

                             List_of_genre  \
0          ["Action","Adventure","Sci-Fi"]   
1         ['Action', 'Adventure', 'Drama']   
2       ['Action', 'Adventure', 'Fantasy']   
3          ['Action', 'Crime', 'Thriller']   
4           ['Action', 'Drama', 'History']   
...                                    ...   
1109                    ['Crime', 'Drama']   
1110                 ['Drama', 'Thriller']   
1111                            ['Comedy']   
1112  ['Animation', 'Adventure', 'Comedy']   
1113     ['Adventure', 'Drama', 'Western']   

                                   Discription_of_movie     Run_time_in_min  \
0     Set after the battle between Godzilla and the ...                   0   
1     Prequel series to Star Wars' 'Rogue One'. In a...          40 minutes   
2     Jake Sully lives with his newfound family form...  3 hours 12 minutes   
3     A man who believes he has put his mysterious p...  2 hours 12 minutes   
4     As Alfred the Great defends his kingdom from N...              1 hour   
...                                                 ...                 ...   
1109  A young boy, left without attention, delves in...   1 hour 39 minutes   
1110  A nurse is put in charge of a mute actress and...   1 hour 25 minutes   
1111  Born on the original Christmas in the stable n...   1 hour 34 minutes   
1112  A kind-hearted street urchin and a power-hungr...   1 hour 30 minutes   
1113  Lieutenant John Dunbar, assigned to a remote w...    3 hours 1 minute   

                          Language_of_move  \
0                                  English   
1                                  English   
2                                  English   
3     EnglishRussianSpanishGermanUkrainian   
4                             EnglishLatin   
...                                    ...   
1109                         FrenchEnglish   
1110                        SwedishEnglish   
1111                          EnglishLatin   
1112                               English   
1113                    EnglishSiouxPawnee   

                                      Country_of_origin  \
0                   Vancouver, British Columbia, Canada   
1                      Cruachan Reservoir, Scotland, UK   
2         Stone Street Studios, Wellington, New Zealand   
3              Haverhill, Massachusetts, USA(Home Mart)   
4                         Korda Studios, Etyek, Hungary   
...                                                 ...   
1109          Pigalle, Paris 9, Paris, France(location)   
1110                         Fårö, Gotlands län, Sweden   
1111  Amphitheater, Carthage, Tunis, Tunisia(amphith...   
1112  Walt Disney Feature Animation - 500 S. Buena V...   
1113  Badlands National Park, South Dakota, USA(Fort...   

               Budget_of_movie Global_collection  \
0                            0                 0   
1                            0                 0   
2     $350,000,000 (estimated)    $2,320,250,281   
3      $55,000,000 (estimated)      $192,330,738   
4                            0                 0   
...                        ..

In [13]:
df['UniqueID'] = df.reset_index().index + 1

In [14]:
df.to_csv("movieData2.csv",index=False)

In [56]:
thisIsFinalDF = pd.read_csv("movieData2.csv")
thisIsFinalDF

UniqueID                Name_of_movie            Name_of_director  \
0            1  Monarch: Legacy of Monsters                Matt Shakman   
1            2                        Andor              Benjamin Caron   
2            3     Avatar: The Way of Water               James Cameron   
3            4                The Equalizer               Antoine Fuqua   
4            5             The Last Kingdom           Edward Bazalgette   
...        ...                          ...                         ...   
1049      1050                The 400 Blows           François Truffaut   
1050      1051                      Persona              Ingmar Bergman   
1051      1052                Life of Brian                 Terry Jones   
1052      1053                      Aladdin   Ron Clements, John Musker   
1053      1054           Dances with Wolves               Kevin Costner   

                             List_of_genre  \
0          ["Action","Adventure","Sci-Fi"]   
1         ['Action', 'Adventure', 'Drama']   
2       ['Action', 'Adventure', 'Fantasy']   
3          ['Action', 'Crime', 'Thriller']   
4           ['Action', 'Drama', 'History']   
...                                    ...   
1049                    ['Crime', 'Drama']   
1050                 ['Drama', 'Thriller']   
1051                            ['Comedy']   
1052  ['Animation', 'Adventure', 'Comedy']   
1053     ['Adventure', 'Drama', 'Western']   

                                   Discription_of_movie     Run_time_in_min  \
0     Set after the battle between Godzilla and the ...                   0   
1     Prequel series to Star Wars' 'Rogue One'. In a...          40 minutes   
2     Jake Sully lives with his newfound family form...  3 hours 12 minutes   
3     A man who believes he has put his mysterious p...  2 hours 12 minutes   
4     As Alfred the Great defends his kingdom from N...              1 hour   
...                                                 ...                 ...   
1049  A young boy, left without attention, delves in...   1 hour 39 minutes   
1050  A nurse is put in charge of a mute actress and...   1 hour 25 minutes   
1051  Born on the original Christmas in the stable n...   1 hour 34 minutes   
1052  A kind-hearted street urchin and a power-hungr...   1 hour 30 minutes   
1053  Lieutenant John Dunbar, assigned to a remote w...    3 hours 1 minute   

                          Language_of_move  \
0                                  English   
1                                  English   
2                                  English   
3     EnglishRussianSpanishGermanUkrainian   
4                             EnglishLatin   
...                                    ...   
1049                         FrenchEnglish   
1050                        SwedishEnglish   
1051                          EnglishLatin   
1052                               English   
1053                    EnglishSiouxPawnee   

                                      Country_of_origin  \
0                   Vancouver, British Columbia, Canada   
1                      Cruachan Reservoir, Scotland, UK   
2         Stone Street Studios, Wellington, New Zealand   
3              Haverhill, Massachusetts, USA(Home Mart)   
4                         Korda Studios, Etyek, Hungary   
...                                                 ...   
1049          Pigalle, Paris 9, Paris, France(location)   
1050                         Fårö, Gotlands län, Sweden   
1051  Amphitheater, Carthage, Tunis, Tunisia(amphith...   
1052  Walt Disney Feature Animation - 500 S. Buena V...   
1053  Badlands National Park, South Dakota, USA(Fort...   

               Budget_of_movie Global_collection  \
0                            0                 0   
1                            0                 0   
2     $350,000,000 (estimated)    $2,320,250,281   
3      $55,000,000 (estimated)      $192,330,738   
4                            0                 0   
...                        ..

In [36]:
moduleBuilding = thisIsFinalDF.copy()


In [95]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [97]:
# here i have done the staming ie removed the steam words which are plurals or same mining with different words
moduleBuilding["tags"] = moduleBuilding["tags"].apply(stem)

## newDf

### name_of_movies = df["Name_of_movie"]
## poster_url = df["Poster_url_"]
## director_name = df["Name_of_director"]
## list_of_genre = df["List_of_genre"]
## language_of_move = df["Language_of_move"]
## Names_of_Cast = df["Names_of_Cast"]

In [37]:
moduleBuilding.drop(['Run_time_in_min', 'Global_collection', 'Rating_out_of_ten', 'World_Wild_Views', 'Reviews_to_movie','Language_of_move', 'Country_of_origin', 'Budget_of_movie','Release_year','Poster_url_'], axis=1, inplace=True)
# print(newDf.columns)

In [38]:
# Remove square brackets, commas, and single quotes from 'List_of_genre' column
moduleBuilding['List_of_genre'] = moduleBuilding['List_of_genre'].apply(lambda x: x.replace("[", "").replace("]", "").replace(", ", "").replace("'", ""))

# Remove square brackets, commas, and single quotes from 'Names_of_Cast' column
moduleBuilding['Names_of_Cast'] = moduleBuilding['Names_of_Cast'].apply(lambda x: x.replace("[", "").replace("]", "").replace(", ", "").replace("'", ""))


In [39]:
# Remove single quotes, double quotes, and commas from all columns
moduleBuilding = moduleBuilding.map(lambda x: str(x).replace("'", "").replace('"', '').replace(',', '').replace(':',''))

In [41]:
moduleBuilding["tags"] = moduleBuilding["Name_of_movie"] + moduleBuilding["Name_of_director"] + moduleBuilding["List_of_genre"] + moduleBuilding["Names_of_Cast"] +moduleBuilding["Discription_of_movie"]


In [42]:
moduleBuilding =  moduleBuilding[["UniqueID","Name_of_movie","tags" ]]

UniqueID               Name_of_movie  \
0           1  Monarch Legacy of Monsters   
1           2                       Andor   
2           3     Avatar The Way of Water   
3           4               The Equalizer   
4           5            The Last Kingdom   
...       ...                         ...   
1049     1050               The 400 Blows   
1050     1051                     Persona   
1051     1052               Life of Brian   
1052     1053                     Aladdin   
1053     1054          Dances with Wolves   

                                                   tags  
0     Monarch Legacy of Monsters Matt Shakman Action...  
1     Andor Benjamin CaronActionAdventureDramaDiego ...  
2     Avatar The Way of WaterJames CameronActionAdve...  
3     The EqualizerAntoine FuquaActionCrimeThrillerD...  
4     The Last Kingdom Edward BazalgetteActionDramaH...  
...                                                 ...  
1049  The 400 BlowsFrançois TruffautCrimeDramaJean-P...  
1050  PersonaIngmar BergmanDramaThrillerBibi Anderss...  
1051  Life of BrianTerry JonesComedyGraham ChapmanJo...  
1052  Aladdin Ron Clements John MuskerAnimationAdven...  
1053  Dances with WolvesKevin CostnerAdventureDramaW...  

[1054 rows x 3 columns]

In [185]:
dfForModel["Name_of_movie"]
# print(len(dfForModel["Name_of_movie"]))

0       Monarch Legacy of Monsters
1                            Andor
2          Avatar The Way of Water
3                    The Equalizer
4                 The Last Kingdom
                   ...            
1109                 The 400 Blows
1110                       Persona
1111                 Life of Brian
1112                       Aladdin
1113            Dances with Wolves
Name: Name_of_movie, Length: 1054, dtype: object

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity_matrix = cosine_similarity(genre_matrix, genre_matrix)


In [99]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(moduleBuilding['tags']).toarray()  


In [107]:
vector
print(len(vector[0]))

5000


In [108]:
# cv.get_feature_names_out()


In [109]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [111]:
print(similarity)
print(similarity.shape)

[[1.         0.         0.03706247 ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.06666667]
 [0.03706247 0.         1.         ... 0.05063697 0.         0.05063697]
 ...
 [0.         0.         0.05063697 ... 1.         0.         0.06666667]
 [0.         0.         0.         ... 0.         1.         0.05773503]
 [0.         0.06666667 0.05063697 ... 0.06666667 0.05773503 1.        ]]
(1054, 1054)


In [116]:
def recommend(movie):
    allMovies = list()
    
    try:
        index = moduleBuilding[moduleBuilding['Name_of_movie'] == movie].index[0]

        distances = list(enumerate(similarity[index]))
        distances = sorted(distances, key=lambda x: x[1], reverse=True)
        # print(distances)

        # print(f"Top 10 Recommendations for {movie}:")
        for i in distances[1:11]:
            recommended_movie_title = moduleBuilding.iloc[i[0]]['Name_of_movie']
            allMovies.append(recommended_movie_title)
            print(recommended_movie_title)
    except IndexError:
        print(f"Movie '{movie}' not found in the DataFrame.")
    except Exception as e:
        print(f"Error: {str(e)}")
    finally:
        return allMovies






In [78]:
list_of_recommended_movies = recommend("Hunter Killer")
print(list_of_recommended_movies)

movie = thisIsFinalDF["Name_of_movie"]
poster_url = thisIsFinalDF["Poster_url_"]
point = 0

for movie_name in list_of_recommended_movies:
    for i in range(len(movie)):
        if movie_name == movie[i]:
            print(movie[i])
            print(poster_url[i])
            print("*"*80)
        
       
    

['Rush Hour', 'Hunter x Hunter', 'Green Book', 'Captain America The First Avenger', 'U-571', 'Django Unchained', 'Rambo First Blood Part II', 'Greyhound', 'SAS Rogue Heroes', 'Escape from New York']
Rush Hour
https://m.media-amazon.com/images/M/MV5BYWM2NDZmYmYtNzlmZC00M2MyLWJmOGUtMjhiYmQ2OGU1YTE1L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UY281_CR1,0,190,281_.jpg
********************************************************************************
Hunter x Hunter
https://m.media-amazon.com/images/M/MV5BNGM0YTk3MWEtN2JlZC00ZmZmLWIwMDktZTMxZGE5Zjc2MGExXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_QL75_UY281_CR4,0,190,281_.jpg
********************************************************************************
Green Book
https://m.media-amazon.com/images/M/MV5BNDcyYjgyNWUtZTllZi00ZDQ3LThhMzEtOTczMWMyMWY5YWY3XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_QL75_UX190_CR0,1,190,281_.jpg
********************************************************************************
U-571
https://m.media-amazon.com/images/M/MV5BMDE0Yz

In [55]:
# for movie in list_of_recommended_movies:
#     print(movie)

Alien³
Captain Laserhawk A Blood Dragon Remix
New York Ninja
Starship Troopers
Cloverfield
Hunter Killer
Van Helsing
Joy Ride
San Andreas
Dracula 2001


In [79]:
# count = 0
# for movie in dfForModel['Name_of_movie']:
#     movie_to_recommend = movie  # Replace with the actual movie title
#     an = recommend(movie_to_recommend)
#     print(an)
#     print(len(an))
#     count += 1
#     print(count)
#     print("*"*80)

In [101]:
### now i want to find the poster urls
# containerForPoster = list()
# pointer = 0
# for i in range(len(name_of_movies)):
#     if pointer > 9 :
#         break
#     if name_of_movies[i] == ans[pointer]:
#         # append in containerForPoster
#         dict = {
#             "name_of_movies":name_of_movies[i],
#             "poster_of_movies":poster_url[i],
#             "director_name":director_name[i],
#             "list_of_genre":list_of_genre[i],
#             "language_of_move":language_of_move[i],
#             "Names_of_Cast":Names_of_Cast[i]            
#             }
#         pointer += 1
#         containerForPoster.append(dict)


In [121]:
import pickle

# Assuming 'new' is your DataFrame and 'similarity' is the cosine similarity matrix
pickle.dump(moduleBuilding.to_dict(), open('movie_dict.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))


In [119]:
with open('/home/samir/Desktop/ML_project/movie_list.pkl', 'rb') as file:
    model = pickle.load(file)

In [120]:
datafram = pd.DataFrame(model)